from graphics import Canvas

def create_dinosaur(canvas, dino_height, starting_x, starting_y):
    no_of_dino_layers = 20
    block_size = dino_height / no_of_dino_layers

    dino = []

    # dino[0] is the highest point — top-left block of the dino's head, at row y = starting_y

    # following is one of the top-most point (index 0)
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y, starting_x + 11 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y, starting_x + 12 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y, starting_x + 13 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y, starting_x + 14 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y, starting_x + 15 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y, starting_x + 16 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y, starting_x + 17 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 17 * block_size, starting_y, starting_x + 18 * block_size, starting_y + block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 1 * block_size, starting_x + 10 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 1 * block_size, starting_x + 11 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 1 * block_size, starting_x + 12 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 1 * block_size, starting_x + 13 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 1 * block_size, starting_x + 14 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 1 * block_size, starting_x + 15 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y + 1 * block_size, starting_x + 16 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y + 1 * block_size, starting_x + 17 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 17 * block_size, starting_y + 1 * block_size, starting_x + 18 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    # following is one of the right most point (index 17)
    dino.append(canvas.create_rectangle(starting_x + 18 * block_size, starting_y + 1 * block_size, starting_x + 19 * block_size, starting_y + 2 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 2 * block_size, starting_x + 10 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 2 * block_size, starting_x + 11 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 2 * block_size, starting_x + 13 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 2 * block_size, starting_x + 14 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 2 * block_size, starting_x + 15 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y + 2 * block_size, starting_x + 16 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y + 2 * block_size, starting_x + 17 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 17 * block_size, starting_y + 2 * block_size, starting_x + 18 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 18 * block_size, starting_y + 2 * block_size, starting_x + 19 * block_size, starting_y + 3 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 3 * block_size, starting_x + 10 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 3 * block_size, starting_x + 11 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 3 * block_size, starting_x + 12 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 3 * block_size, starting_x + 13 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 3 * block_size, starting_x + 14 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 3 * block_size, starting_x + 15 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y + 3 * block_size, starting_x + 16 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y + 3 * block_size, starting_x + 17 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 17 * block_size, starting_y + 3 * block_size, starting_x + 18 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 18 * block_size, starting_y + 3 * block_size, starting_x + 19 * block_size, starting_y + 4 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 4 * block_size, starting_x + 10 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 4 * block_size, starting_x + 11 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 4 * block_size, starting_x + 12 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 4 * block_size, starting_x + 13 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 4 * block_size, starting_x + 14 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 4 * block_size, starting_x + 15 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y + 4 * block_size, starting_x + 16 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y + 4 * block_size, starting_x + 17 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 17 * block_size, starting_y + 4 * block_size, starting_x + 18 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 18 * block_size, starting_y + 4 * block_size, starting_x + 19 * block_size, starting_y + 5 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 5 * block_size, starting_x + 10 * block_size, starting_y + 6 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 5 * block_size, starting_x + 11 * block_size, starting_y + 6 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 5 * block_size, starting_x + 12 * block_size, starting_y + 6 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 5 * block_size, starting_x + 13 * block_size, starting_y + 6 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 5 * block_size, starting_x + 14 * block_size, starting_y + 6 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 6 * block_size, starting_x + 10 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 6 * block_size, starting_x + 11 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 6 * block_size, starting_x + 12 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 6 * block_size, starting_x + 13 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 6 * block_size, starting_x + 14 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 6 * block_size, starting_x + 15 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 15 * block_size, starting_y + 6 * block_size, starting_x + 16 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 16 * block_size, starting_y + 6 * block_size, starting_x + 17 * block_size, starting_y + 7 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x, starting_y + 7 * block_size, starting_x + block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 7 * block_size, starting_x + 9 * block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 7 * block_size, starting_x + 10 * block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 7 * block_size, starting_x + 11 * block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 7 * block_size, starting_x + 12 * block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 7 * block_size, starting_x + 13 * block_size, starting_y + 8 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x, starting_y + 8 * block_size, starting_x + block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 8 * block_size, starting_x + 8 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 8 * block_size, starting_x + 9 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 8 * block_size, starting_x + 10 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 8 * block_size, starting_x + 11 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 8 * block_size, starting_x + 12 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 8 * block_size, starting_x + 13 * block_size, starting_y + 9 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x, starting_y + 9 * block_size, starting_x + block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 1 * block_size, starting_y + 9 * block_size, starting_x + 2 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 9 * block_size, starting_x + 6 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 9 * block_size, starting_x + 7 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 9 * block_size, starting_x + 8 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 9 * block_size, starting_x + 9 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 9 * block_size, starting_x + 10 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 9 * block_size, starting_x + 11 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 9 * block_size, starting_x + 12 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 9 * block_size, starting_x + 13 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 13 * block_size, starting_y + 9 * block_size, starting_x + 14 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 9 * block_size, starting_x + 15 * block_size, starting_y + 10 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x, starting_y + 10 * block_size, starting_x + block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 1 * block_size, starting_y + 10 * block_size, starting_x + 2 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 2 * block_size, starting_y + 10 * block_size, starting_x + 3 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 10 * block_size, starting_x + 5 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 10 * block_size, starting_x + 6 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 10 * block_size, starting_x + 7 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 10 * block_size, starting_x + 8 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 10 * block_size, starting_x + 9 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 10 * block_size, starting_x + 10 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 10 * block_size, starting_x + 11 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 10 * block_size, starting_x + 12 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 10 * block_size, starting_x + 13 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 14 * block_size, starting_y + 10 * block_size, starting_x + 15 * block_size, starting_y + 11 * block_size, 'black', 'black'))
    # following is one of the left_most point (index 98)
    dino.append(canvas.create_rectangle(starting_x, starting_y + 11 * block_size, starting_x + block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 1 * block_size, starting_y + 11 * block_size, starting_x + 2 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 2 * block_size, starting_y + 11 * block_size, starting_x + 3 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 3 * block_size, starting_y + 11 * block_size, starting_x + 4 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 11 * block_size, starting_x + 5 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 11 * block_size, starting_x + 6 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 11 * block_size, starting_x + 7 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 11 * block_size, starting_x + 8 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 11 * block_size, starting_x + 9 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 11 * block_size, starting_x + 10 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 11 * block_size, starting_x + 11 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 11 * block_size, starting_x + 12 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 11 * block_size, starting_x + 13 * block_size, starting_y + 12 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x, starting_y + 12 * block_size, starting_x + block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 1 * block_size, starting_y + 12 * block_size, starting_x + 2 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 2 * block_size, starting_y + 12 * block_size, starting_x + 3 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 3 * block_size, starting_y + 12 * block_size, starting_x + 4 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 12 * block_size, starting_x + 5 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 12 * block_size, starting_x + 6 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 12 * block_size, starting_x + 7 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 12 * block_size, starting_x + 8 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 12 * block_size, starting_x + 9 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 12 * block_size, starting_x + 10 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 12 * block_size, starting_x + 11 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 12 * block_size, starting_x + 12 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 12 * block_size, starting_y + 12 * block_size, starting_x + 13 * block_size, starting_y + 13 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 1 * block_size, starting_y + 13 * block_size, starting_x + 2 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 2 * block_size, starting_y + 13 * block_size, starting_x + 3 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 3 * block_size, starting_y + 13 * block_size, starting_x + 4 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 13 * block_size, starting_x + 5 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 13 * block_size, starting_x + 6 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 13 * block_size, starting_x + 7 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 13 * block_size, starting_x + 8 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 13 * block_size, starting_x + 9 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 13 * block_size, starting_x + 10 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 13 * block_size, starting_x + 11 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 13 * block_size, starting_x + 12 * block_size, starting_y + 14 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 2 * block_size, starting_y + 14 * block_size, starting_x + 3 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 3 * block_size, starting_y + 14 * block_size, starting_x + 4 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 14 * block_size, starting_x + 5 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 14 * block_size, starting_x + 6 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 14 * block_size, starting_x + 7 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 14 * block_size, starting_x + 8 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 14 * block_size, starting_x + 9 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 14 * block_size, starting_x + 10 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 14 * block_size, starting_x + 11 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 11 * block_size, starting_y + 14 * block_size, starting_x + 12 * block_size, starting_y + 15 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 3 * block_size, starting_y + 15 * block_size, starting_x + 4 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 15 * block_size, starting_x + 5 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 15 * block_size, starting_x + 6 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 15 * block_size, starting_x + 7 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 7 * block_size, starting_y + 15 * block_size, starting_x + 8 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 15 * block_size, starting_x + 9 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 15 * block_size, starting_x + 10 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 15 * block_size, starting_x + 11 * block_size, starting_y + 16 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 16 * block_size, starting_x + 5 * block_size, starting_y + 17 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 16 * block_size, starting_x + 6 * block_size, starting_y + 17 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 6 * block_size, starting_y + 16 * block_size, starting_x + 7 * block_size, starting_y + 17 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 8 * block_size, starting_y + 16 * block_size, starting_x + 9 * block_size, starting_y + 17 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 16 * block_size, starting_x + 10 * block_size, starting_y + 17 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 17 * block_size, starting_x + 5 * block_size, starting_y + 18 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 17 * block_size, starting_x + 6 * block_size, starting_y + 18 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 17 * block_size, starting_x + 10 * block_size, starting_y + 18 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 18 * block_size, starting_x + 5 * block_size, starting_y + 19 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 18 * block_size, starting_x + 10 * block_size, starting_y + 19 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 4 * block_size, starting_y + 19 * block_size, starting_x + 5 * block_size, starting_y + 20 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 5 * block_size, starting_y + 19 * block_size, starting_x + 6 * block_size, starting_y + 20 * block_size, 'black', 'black'))
    dino.append(canvas.create_rectangle(starting_x + 9 * block_size, starting_y + 19 * block_size, starting_x + 10 * block_size, starting_y + 20 * block_size, 'black', 'black'))
    # following is one of the bottom-most points (index 166)
    dino.append(canvas.create_rectangle(starting_x + 10 * block_size, starting_y + 19 * block_size, starting_x + 11 * block_size, starting_y + 20 * block_size, 'black', 'black'))

    return dino